# Generated by Django 3.0.11 on 2021-03-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'celebracion',
                'verbose_name_plural': 'celebraciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Este color ya esta registrado.'}, max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya esta registrado este tipo de producto.'}, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(error_messages={'unique': 'Esta talla ya esta registrada.'}, max_length=15, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ManyToManyField(to='shirts.Producto')),
            ],
            options={
                'verbose_name': 'talla',
                'verbose_name_plural': 'tallas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, error_messages={'unique': 'Ya esta esa id.'}, primary_key=True, serialize=False, unique=True)),
                ('publico', models.CharField(blank=True, choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('NIÑA', 'Niña'), ('NIÑO', 'Niño')], max_length=7, null=True)),
                ('celebracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shirts.Celebration')),
                ('colores', models.ManyToManyField(editable=False, related_name='Colores', to='shirts.Color')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shirts.Producto')),
                ('talla', models.ManyToManyField(related_name='Tallas', to='shirts.Talla')),
            ],
            options={
                'ordering': ['producto', 'publico', 'celebracion', '-id'],
            },
        ),
    ]
