# Generated by Django 3.0.11 on 2021-02-10 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebracion', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['celebracion'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['color'],
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=15)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.AutoField(auto_created=True, error_messages={'unique': 'Ya esta esa id.'}, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('NIÑA', 'Niña'), ('NIÑO', 'Niño')], max_length=7, null=True)),
                ('celebracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shirts.Celebration')),
                ('colores', models.ManyToManyField(editable=False, related_name='Colores', to='shirts.Color')),
                ('talla', models.ManyToManyField(related_name='Tallas', to='shirts.Talla')),
            ],
            options={
                'ordering': ['tipo', 'celebracion', '-id'],
            },
        ),
    ]
