# Generated by Django 3.0.11 on 2021-03-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shirts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='camisas')),
                ('orden', models.PositiveIntegerField(blank=True)),
                ('imagen_principal', models.CharField(choices=[('NO', 'No'), ('SI', 'Si')], default='NO', max_length=2)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirts.Color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirts.Item')),
            ],
            options={
                'verbose_name': 'Imagenes',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['item', 'color', 'orden'],
            },
        ),
    ]
