# Generated by Django 3.0.11 on 2021-01-29 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shirts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(error_messages={'unique': 'Ya existe ese color'}, max_length=15, unique=True)),
            ],
            options={
                'ordering': ['color'],
            },
        ),
        migrations.CreateModel(
            name='Imagene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='camisas')),
                ('orden', models.PositiveIntegerField(blank=True)),
                ('imagen_principal', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('camisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirts.Camisa')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.Colore')),
            ],
            options={
                'ordering': ['camisa', 'color', 'orden'],
            },
        ),
    ]
